// <auto-generated />
namespace LuckLogsApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Custom2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Custom2));
        
        string IMigrationMetadata.Id
        {
            get { return "201710140613152_Custom2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
